version: '3.1'

services:

  mongo:
    image: "mongo:3.6.15"
    ports: 
      - 27017:27017
    volumes:
      - /workspace/way-work/data/mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: waychan23
      MONGO_INITDB_ROOT_PASSWORD: 123456 

# MongoDB Web管理工具，如果有需要，请取消注释。
#  mongo-express:
#    image: "mongo-express:latest"
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: waychan23
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456

  nginx:
    image: "nginx:latest"
    ports: 
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
      - /etc/localtime:/etc/localtime

  docgaga-server:
    image: "docgaga-server:0.0.1"
    ports:
      - 3333:3333
    volumes:
      - ./conf/docgaga-server/runtime-conf.js:/workspace/docgaga-server/server/config/runtime-conf.js

  docgaga-crx-server:
    image: "docgaga-crx-server:0.0.1"
    ports: 
      - 3334:3334
    volumes:
      - ./conf/docgaga-crx-server/runtime-conf.js:/workspace/docgaga-crx-server/server/config/runtime-conf.js
